spring:
  application:
    name: SalesService
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        orderPlaced: # [MessageChannel]
          destination: order.placed
        orderModified: # [MessageChannel]
          destination: order.modified
        orderCancelled: # [MessageChannel]
          destination: order.cancelled
  zipkin:
    sender:
      type: rabbit